#The name of the workflow as it appears in the GitHub Actions tab
name: GitHub Actions Demo

# Specifies the event that triggers this automated workflow
on:
  push:
    branches: [ "main" ]

# Defines the sequence of tasks to execute
jobs:
  build-and-test:
    # The type of virtual machine environment the job will run on
    runs-on: ubuntu-latest

    # The individual steps to be executed sequentially in this job
    steps:
      # Step 1: Checks out your repository code onto the runner machine
      - name: Check out repository code
        uses: actions/checkout@v4

      # Step 2: Runs a standard shell command
      - name: Run a diagnostic test command
        run: echo "Hello World! The workflow is
